# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GastronomiaDistritos
                                 A QGIS plugin
 Pratos típicos de cada distrito de Portugal
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-24
        copyright            : (C) 2021 by João Ricardo e Cláudia Palma
        email                : a83553@alunos.uminho.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GastronomiaDistritos class from file GastronomiaDistritos.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gastronomia_distritos import GastronomiaDistritos

    return GastronomiaDistritos(iface)
